[tool.poetry]
name = "graphqlestudo"
version = "0.1.0"
description = ""
authors = ["Fabio Moraes <fabio.moraes@radixeng.com.br>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.14"
fastapi = "^0.136"
fastapi-cli = "^0.0.20"
strawberry-graphql = "^0.314"
uvicorn = { extras = ["standard"], version = "^0.46" }
pydantic = "^2.11"
email-validator = "^2.2"
python-dotenv = "^1.1.1"
ibis-framework = {extras = ["trino"], version = "^12.0.0"}

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
pytest-cov = "^6.3.0"
ruff = "^0.13.0"

# -----------------------------
# COVERAGE
# -----------------------------
[tool.coverage.run]
branch = true
omit = ["app/main.py"]

[tool.coverage.report]
exclude_also = ["no cover: start(?s:.)*?no cover: stop"]
ignore_errors = true

[tool.coverage.html]
directory = "htmlcov"

[tool.coverage.xml]
output = "coverage.xml"

# -----------------------------
# RUFF
# -----------------------------
[tool.ruff]
exclude = ["alembic"]

[tool.ruff.lint]
select = ["E","W","F","I","B","C4","UP","ANN"]
ignore = ["E501","B008","C901","W191"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
"tests/**" = ["S"]
"scripts/**" = ["S"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"